// <auto-generated />
using System;
using DocumentAutomation.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DocumentAutomation.Persistence.Migrations
{
    [DbContext(typeof(DocumentAutomationDbContext))]
    [Migration("20260405152038_InitialProductFoundation")]
    partial class InitialProductFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentAutomation.Domain.Documents.GeneratedDocumentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedByUserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OutputRelativePath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("ProjectRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("TemplateDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Warnings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("generated_documents", (string)null);
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Documents.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("LeadEngineer")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime?>("TestDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.ToTable("projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52fb7817-f0c2-4e20-b4a0-3ce3ea1d8623"),
                            CustomerName = "Contoso Power Systems",
                            LeadEngineer = "Elif Kaya",
                            Metadata = "{\"project.name\":\"Document Automation Foundation\",\"project.code\":\"PRJ-001\",\"project.customer\":\"Contoso Power Systems\",\"project.lead_engineer\":\"Elif Kaya\",\"project.test_date\":\"2026-04-07\"}",
                            ProjectCode = "PRJ-001",
                            ProjectName = "Document Automation Foundation",
                            TestDate = new DateTime(2026, 4, 7, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a44cb6f0-c52b-4c38-9a55-0fc33bd7ec4b"),
                            Description = "View users.",
                            Name = "users.view"
                        },
                        new
                        {
                            Id = new Guid("d4579347-7164-4123-943d-f188c4b9787f"),
                            Description = "Manage users.",
                            Name = "users.manage"
                        },
                        new
                        {
                            Id = new Guid("1a8fe1d8-c4d2-42a7-b39d-e4c657bf4ea5"),
                            Description = "Manage roles.",
                            Name = "roles.manage"
                        },
                        new
                        {
                            Id = new Guid("e5a7dae4-5d4c-4f32-b856-fca0ec9aa4ff"),
                            Description = "View templates.",
                            Name = "templates.view"
                        },
                        new
                        {
                            Id = new Guid("5fdb2c7b-1c58-46ae-b54e-b9f8c155b846"),
                            Description = "Manage templates.",
                            Name = "templates.manage"
                        },
                        new
                        {
                            Id = new Guid("be1c8999-d915-4d6f-aeb8-04bf66e6ec31"),
                            Description = "Generate documents.",
                            Name = "documents.generate"
                        },
                        new
                        {
                            Id = new Guid("c3de4ae4-c931-49a3-a271-2a43630dcd4d"),
                            Description = "Approve generated documents.",
                            Name = "documents.approve"
                        },
                        new
                        {
                            Id = new Guid("1e562906-10a0-46d0-8581-e7fb5989555c"),
                            Description = "View projects.",
                            Name = "projects.view"
                        },
                        new
                        {
                            Id = new Guid("0e3968f2-d4b0-49cf-99ed-f2e915c5d1b6"),
                            Description = "Edit project data.",
                            Name = "projects.edit"
                        },
                        new
                        {
                            Id = new Guid("f74fdd91-bc0e-4b42-a2a1-86372ac7c4ee"),
                            Description = "Edit restricted fields.",
                            Name = "fields.edit.restricted"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            Description = "Full administration access.",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("b2752865-e4e0-45ca-bf20-6f835d7d516f"),
                            Description = "Manages templates and mappings.",
                            Name = "Designer"
                        },
                        new
                        {
                            Id = new Guid("19c459a6-7b16-49bd-9df6-46e773f53a33"),
                            Description = "Prepares data and generates documents.",
                            Name = "SystemEngineer"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("a44cb6f0-c52b-4c38-9a55-0fc33bd7ec4b")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("d4579347-7164-4123-943d-f188c4b9787f")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("1a8fe1d8-c4d2-42a7-b39d-e4c657bf4ea5")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("e5a7dae4-5d4c-4f32-b856-fca0ec9aa4ff")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("5fdb2c7b-1c58-46ae-b54e-b9f8c155b846")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("be1c8999-d915-4d6f-aeb8-04bf66e6ec31")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("c3de4ae4-c931-49a3-a271-2a43630dcd4d")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("1e562906-10a0-46d0-8581-e7fb5989555c")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("0e3968f2-d4b0-49cf-99ed-f2e915c5d1b6")
                        },
                        new
                        {
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1"),
                            PermissionId = new Guid("f74fdd91-bc0e-4b42-a2a1-86372ac7c4ee")
                        },
                        new
                        {
                            RoleId = new Guid("b2752865-e4e0-45ca-bf20-6f835d7d516f"),
                            PermissionId = new Guid("e5a7dae4-5d4c-4f32-b856-fca0ec9aa4ff")
                        },
                        new
                        {
                            RoleId = new Guid("b2752865-e4e0-45ca-bf20-6f835d7d516f"),
                            PermissionId = new Guid("5fdb2c7b-1c58-46ae-b54e-b9f8c155b846")
                        },
                        new
                        {
                            RoleId = new Guid("b2752865-e4e0-45ca-bf20-6f835d7d516f"),
                            PermissionId = new Guid("1e562906-10a0-46d0-8581-e7fb5989555c")
                        },
                        new
                        {
                            RoleId = new Guid("19c459a6-7b16-49bd-9df6-46e773f53a33"),
                            PermissionId = new Guid("1e562906-10a0-46d0-8581-e7fb5989555c")
                        },
                        new
                        {
                            RoleId = new Guid("19c459a6-7b16-49bd-9df6-46e773f53a33"),
                            PermissionId = new Guid("0e3968f2-d4b0-49cf-99ed-f2e915c5d1b6")
                        },
                        new
                        {
                            RoleId = new Guid("19c459a6-7b16-49bd-9df6-46e773f53a33"),
                            PermissionId = new Guid("e5a7dae4-5d4c-4f32-b856-fca0ec9aa4ff")
                        },
                        new
                        {
                            RoleId = new Guid("19c459a6-7b16-49bd-9df6-46e773f53a33"),
                            PermissionId = new Guid("be1c8999-d915-4d6f-aeb8-04bf66e6ec31")
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("37a6f5f6-8529-4ff4-a368-21440dad6370"),
                            DisplayName = "Admin User",
                            IsActive = true,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("86c2917a-3a94-44cc-8cb8-7ee0254e6a39"),
                            DisplayName = "Template Designer",
                            IsActive = true,
                            UserName = "designer"
                        },
                        new
                        {
                            Id = new Guid("0d67cc67-ae3a-4cba-a771-71d05d0c4205"),
                            DisplayName = "System Engineer",
                            IsActive = true,
                            UserName = "engineer"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("37a6f5f6-8529-4ff4-a368-21440dad6370"),
                            RoleId = new Guid("64f75d40-bca0-4e84-8e16-2f4e507d2da1")
                        },
                        new
                        {
                            UserId = new Guid("86c2917a-3a94-44cc-8cb8-7ee0254e6a39"),
                            RoleId = new Guid("b2752865-e4e0-45ca-bf20-6f835d7d516f")
                        },
                        new
                        {
                            UserId = new Guid("0d67cc67-ae3a-4cba-a771-71d05d0c4205"),
                            RoleId = new Guid("19c459a6-7b16-49bd-9df6-46e773f53a33")
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Templates.TemplateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.HasKey("Id");

                    b.ToTable("template_definitions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            CreatedAtUtc = new DateTime(2026, 4, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Demo template for the first product foundation.",
                            DocumentType = "AcceptanceReport",
                            IsActive = true,
                            Name = "System Acceptance Report",
                            RelativePath = "system-acceptance-report.docx"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Templates.TemplateFieldDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowSaveBackToProject")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DatabaseKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("EditablePermissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EditableRoles")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EditorHint")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PersistenceKey")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Section")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SourcePriority")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TemplateDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValidationHints")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VisiblePermissions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("VisibleRoles")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("TemplateDefinitionId", "FieldKey")
                        .IsUnique();

                    b.ToTable("template_fields", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a5187d2-3fa8-4ddd-80c4-c001debe4df6"),
                            AllowSaveBackToProject = false,
                            AllowedValues = "[]",
                            Category = "Identity",
                            DatabaseKey = "project.name",
                            DisplayName = "Project Name",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "project_name",
                            FieldType = "Text",
                            IsRequired = true,
                            Order = 1,
                            Section = "Project",
                            SourcePriority = "[\"Database\",\"Default\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("38183582-0d4e-45bb-9a81-eab16ff1e44c"),
                            AllowSaveBackToProject = false,
                            AllowedValues = "[]",
                            Category = "Identity",
                            DatabaseKey = "project.code",
                            DisplayName = "Project Code",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "project_code",
                            FieldType = "Text",
                            IsRequired = true,
                            Order = 2,
                            Section = "Project",
                            SourcePriority = "[\"Database\",\"Default\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("a93d4890-9bb5-4ead-8d98-beac04e48709"),
                            AllowSaveBackToProject = false,
                            AllowedValues = "[]",
                            Category = "Schedule",
                            DatabaseKey = "project.test_date",
                            DisplayName = "Test Date",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "test_date",
                            FieldType = "Date",
                            IsRequired = true,
                            Order = 3,
                            Section = "Project",
                            SourcePriority = "[\"Database\",\"Default\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("d58164c7-c47f-4b46-a835-642bc84e0bcb"),
                            AllowSaveBackToProject = false,
                            AllowedValues = "[]",
                            Category = "People",
                            DatabaseKey = "project.lead_engineer",
                            DisplayName = "Lead Engineer",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "lead_engineer",
                            FieldType = "Text",
                            IsRequired = true,
                            Order = 4,
                            Section = "Project",
                            SourcePriority = "[\"Database\",\"Default\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("12752c1a-4c1f-4b10-be1f-6028fbdbb0d0"),
                            AllowSaveBackToProject = false,
                            AllowedValues = "[]",
                            Category = "Audit",
                            DatabaseKey = "system.current_user",
                            DisplayName = "Prepared By",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "system.current_user",
                            FieldType = "Text",
                            IsRequired = true,
                            Order = 5,
                            Section = "Workflow",
                            SourcePriority = "[\"Computed\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("0bd1b7df-8ca2-4ef9-bb51-18446133593a"),
                            AllowSaveBackToProject = false,
                            AllowedValues = "[]",
                            Category = "Audit",
                            DatabaseKey = "system.generated_on",
                            DisplayName = "Generated On",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "system.generated_on",
                            FieldType = "Date",
                            IsRequired = true,
                            Order = 6,
                            Section = "Workflow",
                            SourcePriority = "[\"Computed\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("28331e6f-b8ec-4f7d-b8dd-05a36d8ffbfc"),
                            AllowSaveBackToProject = true,
                            AllowedValues = "[]",
                            Category = "Content",
                            DefaultValue = "Initial summary goes here.",
                            DisplayName = "Summary Note",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "summary_note",
                            FieldType = "MultiLineText",
                            IsRequired = true,
                            Order = 7,
                            Section = "Report",
                            SourcePriority = "[\"Database\",\"Default\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("a26151a2-7bee-425a-81b0-1a80c3fc0aa5"),
                            AllowSaveBackToProject = false,
                            AllowedValues = "[]",
                            Category = "Evidence",
                            DisplayName = "Test Setup Image",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "image:test_setup",
                            FieldType = "Image",
                            IsRequired = true,
                            Order = 8,
                            Section = "Report",
                            SourcePriority = "[\"Database\",\"Default\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("ad10ce37-b2f8-4068-a831-c47a84357f35"),
                            AllowSaveBackToProject = false,
                            AllowedValues = "[]",
                            Category = "Evidence",
                            DisplayName = "Test Results Table",
                            EditablePermissions = "[]",
                            EditableRoles = "[]",
                            FieldKey = "table:test_results",
                            FieldType = "Table",
                            IsRequired = true,
                            Order = 9,
                            Section = "Report",
                            SourcePriority = "[\"Database\",\"Default\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        },
                        new
                        {
                            Id = new Guid("2962d966-bca8-48a8-b1da-be023f8c0ab0"),
                            AllowSaveBackToProject = true,
                            AllowedValues = "[]",
                            Category = "Approval",
                            DisplayName = "Approval Note",
                            EditablePermissions = "[\"fields.edit.restricted\"]",
                            EditableRoles = "[]",
                            FieldKey = "approval_note",
                            FieldType = "MultiLineText",
                            IsRequired = true,
                            Order = 10,
                            Section = "Report",
                            SourcePriority = "[\"Database\",\"Default\"]",
                            TemplateDefinitionId = new Guid("33f0c241-c725-4919-9a57-e6a7925a2036"),
                            ValidationHints = "{}",
                            VisiblePermissions = "[]",
                            VisibleRoles = "[]"
                        });
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.RolePermission", b =>
                {
                    b.HasOne("DocumentAutomation.Domain.Security.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentAutomation.Domain.Security.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.UserRole", b =>
                {
                    b.HasOne("DocumentAutomation.Domain.Security.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocumentAutomation.Domain.Security.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Templates.TemplateFieldDefinition", b =>
                {
                    b.HasOne("DocumentAutomation.Domain.Templates.TemplateDefinition", "TemplateDefinition")
                        .WithMany("Fields")
                        .HasForeignKey("TemplateDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TemplateDefinition");
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Security.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("DocumentAutomation.Domain.Templates.TemplateDefinition", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
